version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: smanioto
      MONGO_INITDB_ROOT_PASSWORD: smanioto

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: smanioto
      ME_CONFIG_MONGODB_ADMINPASSWORD: smanioto
