version: '3.3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'ds-mysql'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'ds-mysql'
      MYSQL_ROOT_PASSWORD: '321daniel'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
